jeff-hykin/cpp-textmate-grammar

.vscodeignore

Per #103, and https://code.visualstudio.com/api/working-with-extensions/bundling-extension#publishing
`.vscodeignore` should be updated to exclude `.vscode` and source files.

Create .vscodeignore #103

---

CONTRIBUTING.md

Adds the following information to CONTRIBUTING.md:
- Differences between readable grammars and textmate grammars
- How to use readable regular expressions
- Explanation of unit testing
- A short explanation of the integration testing
- A list of external resources

Add more information to CONTRIBUTING.md

---

cpp/generate.rb
syntaxes/cpp.tmLanguage.json
syntaxes/cpp.tmLanguage.yaml
test/specs/issues/017.cpp.yaml

This fixes the last issue of #17, function names.
The pattern on line 3012 was made non-possessive due to #127, but that did not affect the tests.

make functions support universal character sets #17

---

cpp/generate.rb
cpp/tags.txt
syntaxes/cpp.tmLanguage.json
syntaxes/cpp.tmLanguage.yaml
test/specs/issues/015.cpp.yaml
test/specs/vscode/test.cpp.json

In the example
class Foo {
public:
/* snip */
};
public had the scope storage.type.modifier.access.control.public:.
even worse when there is a space between public and : public had the scope storage.type.modifier.access.control.public.cpp :.cpp.
This PR prevents the `:` from ending up as part of the scope name.

fix access-specifier scope has colon

---

package-lock.json
package.json

The marketplace has version 1.8.14, but that does not exist in the source code, this PR performs a version bump so that they are in sync again.
Additionally, this PR tries to prevent reoccurrence of https://github.com/jeff-hykin/cpp-textmate-grammar/issues/150#issuecomment-490718510 where a published version does not have the updated syntax files. This PR ensures that `npm run build` is ran before publishing to the marketplace and after a version bump.
The second commit of this PR was created by `npm version`

version bump to match match marketplace

---

textmate_tools.rb

This fixes #163.
Any pattern mutation done by `#to_tag` is now supported in start/end patterns.

Allow back references in pattern range

---

package-lock.json
package.json
test/src/arguments.js
test/src/commands/test.js
test/src/pattern-coverage/onigScanner.js
test/src/pattern-coverage/oniguruma-decorator.js
test/src/pattern-coverage/patternCoverage.js
test/src/pattern-coverage/rewriteGrammar.js
test/src/registry.js

This PR adds a pattern coverage report to the end of npm test. Example output:
This was achieved by wrapping the requested OnigLib with a object that returns a custom implementation of an OnigScanner. This scanner manually tests for the matching pattern. By doing this the custom scanner can record what patterns were chosen and what patterns failed to match at all. To ensure that the test quality is not compromised. A genuine OnigScanner is used to give the results to vscode-textmate. A comment containing the original location of each pattern is added in by rewriteGrammar to different patterns that are identical but in different locations,

Add regex pattern coverage

---

package.json
test/src/arguments.js
test/src/commands/test.js
test/src/pattern-coverage/patternCoverage.js

This provides a count of the patterns that were never considered.
A pattern is considered to be never considered if it has no counts for, match failure, match not chosen, or match chosen.

add count of patterns never considered

---

cpp/generate.rb
cpp/tags.txt
syntaxes/cpp.tmLanguage.json
syntaxes/cpp.tmLanguage.yaml
test/fixtures/features/typedef_alias.cpp
test/specs/features/typedef_alias.cpp.yaml
test/src/generateSpec.js

if typedef is followed by `/struct|class|union/` then the declarators after it are markes as type aliases.
This is a part of #138

add highlighting for typedef when used before class/struct/union

---

lint/index.js
lint/linters/spell-check.js
lint/linters/unresolved.js
package-lock.json
package.json

This adds a simple 2 pass linter over the produced grammar.
The linter is given an entire textmate rule and is allowed to keep context.
This is used in this commit to check for unresolved and unused names.
Linters could be added to check scope names for spelling mistakes, or consistency.
There could be a linter to ensure `null` is never a key as that breaks vscode-textmate.
Fixes: #125
Sample Output:

add linter

---

source/languages/cpp/generate.rb
syntaxes/cpp.tmLanguage.json
syntaxes/cpp.tmLanguage.yaml
test/fixtures/issues/vs-cpp-3703.cpp
test/specs/issues/vs-cpp-3703.cpp.yaml

This fixes https://github.com/microsoft/vscode-cpptools/issues/3703
This is a part of #201

Allow string context to use character literals

---

language_tags/cpp.txt
scripts/generate.rb
scripts/lint.rb
source/languages/cpp/generate.rb
syntaxes/cpp.tmLanguage.json
syntaxes/cpp.tmLanguage.yaml
test/fixtures/issues/080.cpp
test/specs/issues/080.cpp.yaml
test/specs/vscode/misc.mm.yaml
test/specs/vscode/misc001.cpp.yaml
test/specs/vscode/misc004.m.yaml

destructors are not allowed to take parameters so a range is not needed.
destructor_proptype was an unneeded pattern.
prevents matching foo::~bar() as a single function name. Instead, its matched as a scope resolution and ~foo()
Part of #80
The generate script was made to just return false on error. See the commit message for why.

Add destructor pattern

---

source/languages/cpp/generate.rb
syntaxes/cpp.tmLanguage.json
syntaxes/cpp.tmLanguage.yaml
test/fixtures/issues/224.cpp
test/specs/issues/224.cpp.yaml

Similar to #131, this prevents a lambda from following &.
Fixes: #224

prevent lambda from succeeding `&`

---

source/languages/cpp/generate.rb
syntaxes/cpp.tmLanguage.json
syntaxes/cpp.tmLanguage.yaml
test/fixtures/issues/222.cpp

When the source wrapper pattern consumes a character it makes patterns that match using the start anchor no longer work when that pattern is the first line. This PR modifies source_pattern to not consume any characters and provides an end pattern that is not possible to match. These two changes combined, ensure that the source wrapper matches every part of the document.
Fixes: #222

make source_wrapper never consume characters

---

test/source/report/onig_scanner.js
test/source/report/oniguruma_decorator.js

The record/report feature of the tests would choke when the grammar has a rule with an empty `patterns` key. This PR fixes that

handle empty patterns when making report

---

source/languages/cpp/generate.rb

Updates the `@std_space` pattern to match one or more of:
- spaces
- inline comments
- or word boundaries
As nothing currently uses `@std_space` This poses not backward compatibility issues.
Unit testing has been added to `@std_space`
Fixes #232

update @std_space pattern

---

source/languages/cpp/generate.rb

It looks like I forgot to push the commit that adds `:zeroLengthStart?: true` to the block finder head and source pattern.
Those are the only two pattern where there is a purposeful match of nothing.

add :zeroLengthStart?: true to source and blockFinderFor head

---

source/languages/cpp/generate.rb
syntaxes/cpp.tmLanguage.json
syntaxes/cpp.tmLanguage.yaml
test/specs/features/constructors.cpp.yaml
test/specs/issues/071.cpp.yaml
test/specs/issues/082.cpp.yaml
test/specs/vscode/example.cpp.yaml

The keyword `typename` signals that the next qualified identifier is a type.
That information is used in this PR to signal that a qualified_type follows `typename`.
This has minimal regression of tags. In templates preceding scopes have their scope changed from `entity.name.scope-resolution.template.call` to `entity.name.scope-resolution`. This should hopefully be resolved when templates are fixed.
This is part of #138.
State | Image
------|------
Before |  ![Screenshot from 2019-06-30 11-31-25](https://user-images.githubusercontent.com/714007/60400587-b5a60980-9b2a-11e9-997b-474d7822d3c0.png)
After | ![Screenshot from 2019-06-30 11-32-55](https://user-images.githubusercontent.com/714007/60400598-d3736e80-9b2a-11e9-9b43-19090f3e643b.png)

ensure a type always follows typename

---

test/source/generate_spec.js
test/specs/issues/134.cpp.yaml
test/specs/vscode/misc.mm.yaml
test/specs/vscode/misc005.cpp.yaml

difference is not acceptable to split scopes as scopes may be
duplicated.
The following tests were regenerated:
- issues/134.cpp
- vscode/misc.mm
- vscode/misc005.cpp
Fixes, part of #272 misc004.m is still broken.

Fix spec generator. update bad tests

---

package-lock.json
package.json
source/languages/cpp/generate.rb
source/textmate_tools.rb
syntaxes/cpp.tmLanguage.json
syntaxes/cpp.tmLanguage.yaml
test/fixtures/issues/vs-76430.cpp
test/specs/issues/034.cpp.yaml
test/specs/issues/136.cpp.yaml
test/specs/issues/vs-76430.cpp.yaml

If a macro is on a single line. Then that line can be matched and
reparsed. This has the effect of preventing any patternRanges
from leaking past the macro.
This also adds a @end_of_line named pattern. This is needed as the unit tests and vscode-textmate have different ideas of what counts as the end of the line.
In vscode-textmate `/foo$/` will not match as vscode-textmate considers the line separator `\n` to be a part of the line. However `/foo\n` will make the pattern more difficult to unit test because `\n` would need to be added to each test. `@end_of_line` matches both.
`@start_of_line`m which is an alias for `/^/` was added for feature parity with `@{start,end}_of_document`
Fixes: microsoft/vscode/issues/76430

End ranges when singe line macro terminates.

---

.editorconfig
.vscode/extensions.json

This adds a `.editorconfig` file to provide basic formatting for all files.
The current editorconfig settings match the current formatting.

Add .editorconfig

---

test/source/paths.js

Array.proptotype.flat was only added to nodejs 11.0. LTS versions 8.x and
10.x are still actively maintained and should not be excluded when there
is an equivalent function.

make paths.js not rely on node >= 11.0

---

language_tags/cpp.txt
source/languages/cpp/generate.rb
syntaxes/cpp.tmLanguage.json
syntaxes/cpp.tmLanguage.yaml
syntaxes/dockerfile.tmLanguage.json
syntaxes/dockerfile.tmLanguage.yaml
test/fixtures/features/typedef_alias.cpp
test/specs/features/typedef_alias.cpp.yaml

This PR marks. `typedef void (*genptr)();` as a type alias.
Affected tests have been updated.

add typedef support for function pointers

---

syntaxes/dockerfile.tmLanguage.json
syntaxes/dockerfile.tmLanguage.yaml
test/source/generate_spec.js
test/specs/vscode/misc004.m.yaml

As part of deciding what scopes have ended, the spec generator incorrectly concluded that scopes the matched after a scope mismatch did not end. This PR fixes that behavior.
fixes: #272

Fix issue with spec generation

---

source/languages/cpp/generate.rb
syntaxes/cpp.tmLanguage.json
syntaxes/cpp.tmLanguage.yaml
test/specs/features/operator_overload.cpp.yaml
test/specs/issues/082.cpp.yaml
test/specs/vscode/example.cpp.yaml
test/specs/vscode/misc005.cpp.yaml

What caused the issue described in https://github.com/jeff-hykin/cpp-textmate-grammar/issues/301#issuecomment-510792204 was that the operator_overload pattern was not updated.

Fix specifiers for operator overloads

---

test/source/report/onig_scanner.js

OnigScanner stops checking early if the earliest possible match has been found. This PR makes the OnigScanner wrapper match that behavior.

make the OnigScanner wrapper match the behavior of the actual OnigScanner

---

language_tags/c.txt
language_tags/cpp.txt
source/languages/c/generate.rb
source/languages/cpp/generate.rb
syntaxes/c.tmLanguage.json
syntaxes/c.tmLanguage.yaml
syntaxes/cpp.tmLanguage.json
syntaxes/cpp.tmLanguage.yaml
test/fixtures/issues/324.cpp
test/specs/features/parameters.cpp.yaml
test/specs/features/preprocessor.cpp.yaml
test/specs/issues/027.c.yaml
test/specs/issues/027.cpp.yaml
test/specs/issues/030.cpp.yaml
test/specs/issues/034.c.yaml
test/specs/issues/136.cpp.yaml
test/specs/issues/324.cpp.yaml
test/specs/vscode/example.cpp.yaml
test/specs/vscode/misc005.cpp.yaml

Fixes #324.
This does not implement multi-line macro argument definitions as described in https://github.com/jeff-hykin/cpp-textmate-grammar/issues/324#issuecomment-514722502

Fix preprocessor macro arguments

---

source/languages/cpp/generate.rb

This PR rewrites the meta_preprocessor_include pattern from a range to a simple match.
---
[[cpp.include]](eel.is/c++draft/cpp.include) Specifies that a header path cannot contain a newline. The original pattern was over matching by being a range.
Additionally, paragraph 4 permits a macro to be used as a the include path. This currently has no highlight for such contructs. 
If the `#include` directive is actively being typed, and as a result is incomplete/ The current grammar would often cause repaints of large swaths of the document. This is not only slow and unnecessary but often annoying.
See https://github.com/textmate/c.tmbundle/issues/66

rewrite include to only be a single line

---

language_tags/cpp.txt
source/languages/cpp/generate.rb
syntaxes/cpp.tmLanguage.json
syntaxes/cpp.tmLanguage.yaml

Add invalid tag for unexpected end of block comment

---

source/textmate_tools.rb

From: https://github.com/jeff-hykin/cpp-textmate-grammar/pull/322#issuecomment-514844216
The append option to retag adds a suffix to every scope, including explicitly set ones. The append option implies `keep: true`.

Add append option to reTag

---

.editorconfig
package.json
test/source/arguments.js
test/source/commands/generate-specs.js
test/source/commands/report.js
test/source/commands/sort-specs.js
test/source/commands/test.js
test/source/get_tests.js
test/source/get_tokens.js
test/source/index.js
test/source/report/onig_scanner.js
test/source/report/recorder.js
test/source/report/reporters/perf.js
test/source/report/reporters/perf2.js
test/source/report/rewrite_grammar.js
test/source/select_tests.js

This change is motivated by the fact that running a reporter on the default fixtures is currently impossible. This was because the reporter choice was a positional argument, therefore the number of positional arguments is never zero when using the reporting feature. Many functions had code to the effect of `argv._.length === 0 || _.include(argv._,fixture)` as a way of filtering fixtures. This prevented positional arguments from being used for non-filtering purposes.
This rewrite has each command register the arguments it takes, this way tools can just look for the `yargs.fixture` to determine how to filter fixtures.
Additionally, the help menu no longer shows options (like `--perf-limit`) that are not relevant to the requested command.

Rewrite test suite to use yarg commands for dispatch

---

test/source/commands/report.js
test/source/generate_spec.js
test/source/get_tokens.js
test/source/test_runner.js

When generating a report, this PR displays an overwritable line number that is currently being processed. This is useful when debugging performance issues of large files, as you can tell when the grammar is stuck or just processing a large number of lines.

Display current line number when making reports

---

test/source/commands/report.js
test/source/report/onig_scanner.js
test/source/report/recorder.js

Changes:
- works with embedded macro grammar
- report total time for a file
- eliminate unneeded onigScanner
I was thinking in a later PR of making part of `npm test` a check that no more than 40% of the time (maybe per file) is spent matching regular expressions.

general improvements to perf tool

---

gem/lib/textmate_grammar/pattern_variations/pattern_range.rb

Adds the option `end_pattern_last` to PatternRange that sets the rule option `applyEndPatternLast` to `1`.
Required for wrappers that consume no characters to work.

Add end_pattern_last to PatternRange

---

gem/lib/textmate_grammar/linters/standard_naming.rb

When the Standard naming linter was added, I only looked at SublimeText's scope naming guide to decide which names were valid. Several existing scope names were not valid under those rules. However, themes are currently using those names and changing them would be an undue burden on theme makers for no real benefit. Therefore this PR adds all scopes names that were previously failing to the list of acceptable scope names.

add existing scope names to standard naming

---

source/languages/objc/examples/examples.m
source/languages/objc/examples/examples.spec.yaml
source/languages/objc/original.tmLanguage.json
source/languages/objcpp/examples/misc.spec.yaml
source/languages/objcpp/original.tmLanguage.json
syntaxes/objc.tmLanguage.json
syntaxes/objcpp.tmLanguage.json

Adds support for the following:
- `__block` storage modifier
- Property attributes: `nonnull`, `nullable`, `null_resettable`, `atomic`, `class`, and `direct`
- Type modifiers: `nonnull`, `nullable`, `_Nonnull`, and `_Nullable`
See the related https://github.com/jeff-hykin/cpp-textmate-grammar/issues/538, although this commit/PR does not add support for the `self`/`super`/`_cmd`.

Support Objective-C nullability, __block, and more property attributes

---

source/languages/objc/examples/examples.spec.yaml
source/languages/objc/examples/misc_002.spec.yaml
source/languages/objc/examples/misc_003.spec.yaml
source/languages/objc/examples/misc_004.spec.yaml
source/languages/objc/original.tmLanguage.json
source/languages/objcpp/examples/examples.spec.yaml
source/languages/objcpp/examples/misc.spec.yaml
source/languages/objcpp/original.tmLanguage.json
syntaxes/objc.tmLanguage.json
syntaxes/objcpp.tmLanguage.json

- Highlight `in` keyword
- Improve `self/super/_cmd` highlighting, previously
it would trigger in an @implementation and a few other places
- Improve detection of Objective-C method calls, previously it would
get mixed up with `meta.bracket.square.access`
Fixes #550 and fixes #538

Improve Objective-C and Objective-C++ highlighting
